
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aybuk
 */
public class puanlama extends javax.swing.JFrame {

    /**
     * Creates new form puanlama
     */
    Connection con;
    private static Statement st;

    public static Connection connect() {

        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/veritabanları", "root", "");
        } catch (Exception e) {
            System.out.println("Veri tabanı bağlantısı başarısız hata:" + e);
        }
        return con;
    }

    public puanlama() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("İzlediğiniz içerik için puan veriniz.");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backkaa.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        ok.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(204, 204, 204));
        ok.setText("OK");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ok)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok))
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
static float veripuan;
    int cont = 0;
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        boolean count = true;
       
       
        try {
            
            String abc = "SELECT * FROM izleme";
            Connection conn = connect();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(abc);
 
            while (rs.next()) {
    
                if (rs.getString("kullaniciemail").equals(Login_Form.girilenmail) && cont == 0) {
               
                    if (rs.getString("progid").equals(izlemepenceresi.idd)) {
                        //0   System.out.println("<kjdnkisvd");
                        count = false;
                        String ekle32 = "UPDATE izleme SET izlemedk=(?) WHERE kullaniciemail=(?)";
                        String s1 = "UPDATE izleme SET progid=(?) WHERE kullaniciemail=(?)";
                        String s2 = "UPDATE izleme SET izlemesn=(?) WHERE kullaniciemail=(?)";
                        String s3 = "UPDATE izleme SET izlemesaat=(?) WHERE kullaniciemail=(?)";
                        String s4 = "UPDATE izleme SET izlemebolum=(?) WHERE kullaniciemail=(?)";
                        String s5 = "UPDATE izleme SET izlemetarih=(?) WHERE kullaniciemail=(?)";
                        String s6 = "UPDATE izleme SET izlemepuan=(?) WHERE kullaniciemail=(?)";

                        try (Connection connna = connect(); PreparedStatement pstmt2 = connna.prepareStatement(ekle32); PreparedStatement pstmt3 = connna.prepareStatement(s1);
                                PreparedStatement pstmt4 = connna.prepareStatement(s2); PreparedStatement pstmt5 = connna.prepareStatement(s3); PreparedStatement pstmt6 = connna.prepareStatement(s4);
                                PreparedStatement pstmt7 = connna.prepareStatement(s5); PreparedStatement pstmt8 = connna.prepareStatement(s6);) {
                            pstmt2.setInt(1, progizleme.gecendk);
                            pstmt2.setString(2, Login_Form.girilenmail);
                            pstmt3.setString(1, izlemepenceresi.idd);
                            pstmt3.setString(2, Login_Form.girilenmail);
                            pstmt4.setInt(1, progizleme.gecensani);
                            pstmt4.setString(2, Login_Form.girilenmail);
                            pstmt5.setInt(1, progizleme.saat);
                            pstmt5.setString(2, Login_Form.girilenmail);
                            pstmt6.setInt(1, progizleme.bolum);
                            pstmt6.setString(2, Login_Form.girilenmail);
                            pstmt7.setString(1, progizleme.sistemTarihiniGetir("yyyy/MM/dd"));
                            pstmt7.setString(2, Login_Form.girilenmail);
                            pstmt8.setFloat(1, veripuan);
                            pstmt8.setString(2, Login_Form.girilenmail);

                            pstmt2.executeUpdate();
                            pstmt3.executeUpdate();
                            pstmt4.executeUpdate();
                            pstmt5.executeUpdate();
                            pstmt6.executeUpdate();
                            pstmt7.executeUpdate();
                            pstmt8.executeUpdate();

                            System.out.println("Veri tabanına eklendiii15:");
                        } catch (Exception ex) {
                            System.out.println("Veri tabanına ekleme başarısız! Hata :" + ex);
                        }

                        cont++;
                    } else if (cont == 1) {
                        String ekle32 = "INSERT INTO izleme (izlemetarih,izlemedk,izlemesn,izlemesaat,izlemebolum,izlemepuan,progid,kullaniciemail) VALUES (?,?,?,?,?,?,?,?)";
                        try (Connection connnb = connect(); PreparedStatement pstmt = connnb.prepareStatement(ekle32);) {
                            pstmt.setString(1, progizleme.sistemTarihiniGetir("yyyy/MM/dd"));
                            pstmt.setInt(2, progizleme.gecendk);
                            pstmt.setInt(3, progizleme.gecensani);
                            pstmt.setInt(4, progizleme.saat);
                            pstmt.setInt(5, progizleme.bolum);
                            pstmt.setFloat(6, veripuan);
                            pstmt.setString(7, izlemepenceresi.idd);
                            pstmt.setString(8, Login_Form.girilenmail);

                            pstmt.executeUpdate();

                            System.out.println("Veri tabanına eklendiii14:");
                        } catch (Exception ex) {
                            System.out.println("Veri tabanına ekleme başarısız! Hata :" + ex);
                        }

                    }
                }

            }
            if (count == true) {

                String ekle3 = "INSERT INTO izleme (izlemetarih,izlemedk,izlemesn,izlemesaat,izlemebolum,izlemepuan,progid,kullaniciemail) VALUES (?,?,?,?,?,?,?,?)";
                System.out.println(ekle3);
                try (Connection connnv = connect(); PreparedStatement pstmt15 = connnv.prepareStatement(ekle3);) {
                    pstmt15.setString(1, progizleme.sistemTarihiniGetir("yyyy/MM/dd"));
                    pstmt15.setInt(2, progizleme.gecendk);
                    pstmt15.setInt(3, progizleme.gecensani);
                    pstmt15.setInt(4, progizleme.saat);
                    pstmt15.setInt(5, progizleme.bolum);
                    pstmt15.setFloat(6, veripuan);
                    pstmt15.setString(7, izlemepenceresi.idd);
                    pstmt15.setString(8, Login_Form.girilenmail);

                    pstmt15.executeUpdate();

                    System.out.println("Veri tabanına eklendiii13:");
                } catch (Exception ex) {
                    System.out.println("Veri tabanına ekleme başarısız! Hata :" + ex);
                }
            }
        } catch (Exception ex) {

            System.err.println("Veri çekme başarısız!");
        }

      izlemepenceresi ab = new izlemepenceresi();
        ab.setVisible(true);
        ab.pack();
        ab.setDefaultCloseOperation(EXIT_ON_CLOSE);
       

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked

        int index = jComboBox1.getSelectedIndex();
        veripuan = Integer.valueOf(index) + 1;
        System.out.println(veripuan);

        float yenipuan;
        int yenip;
        String as = "SELECT * FROM program";

        try {
            Connection conn = connect();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(as);
            while (rs.next()) {

                if (rs.getString("progid").equals(izlemepenceresi.idd)) {
                    yenip = rs.getInt("oylamasayisi") + 1;
                    yenipuan = ((rs.getInt("oylamasayisi") * rs.getFloat("puanlama")) + veripuan) / yenip;
                    String ekle30 = "UPDATE program SET puanlama=(?) WHERE progadi= (?)";
                    String ekle33 = "UPDATE program SET oylamasayisi=(?) WHERE progadi= (?)";
                    System.out.println(ekle30);
                    try (Connection connnvz = connect(); PreparedStatement pstmt = connnvz.prepareStatement(ekle30); PreparedStatement pstmt1 = connnvz.prepareStatement(ekle33);) {
                        pstmt.setFloat(1, yenipuan);
                        pstmt.setString(2, izlemepenceresi.adii);
                        pstmt1.setInt(1, yenip);
                        pstmt1.setString(2, izlemepenceresi.adii);

                        pstmt.executeUpdate();

                        System.out.println("Veri tabanına eklendiii12:");
                    } catch (Exception ex) {
                        System.out.println("Veri tabanına ekleme başarısız! Hata :" + ex);
                    }

                }
            }
          
        } catch (Exception ex) {

            System.err.println("Veri çekme başarısız!65125");
        }


    }//GEN-LAST:event_okMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puanlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puanlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puanlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puanlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Connection c = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/veritabanları", "root", "");
        } catch (Exception e) {
            System.err.println("Veri tabanı bağlantısı başarısız!");
            System.exit(0);
        }
        System.out.println("Veri tabanına başarılı bir şekilde bağlanıldı.");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puanlama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ok;
    // End of variables declaration//GEN-END:variables
}
