
//import static Login_Form.connect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aybuk
 */
public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register_Form
     */
    int sayac = 0;
    int sayac2 = 0;
    Connection con;
    private static Statement st;
    public static String[] secilenler = new String[3];

    public static Connection connect() {

        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/veritabanları", "root", "");
        } catch (Exception e) {
            System.out.println("Veri tabanı bağlantısı başarısız hata:" + e);
        }
        return con;
    }

   /* public static void turleriolustur(){
    String turs="SELECT tipi,progid FROM program";
    try{
    
    ResultSet rs=st.executeQuery(turs);
    while(rs.next()){
    Statement statem
    
    }
    }*/
    
    
    //}
    public Register_Form() {
        con = DbConn.ConnecrDb();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kullaniciisim = new javax.swing.JTextField();
        kullanicimail = new javax.swing.JTextField();
        kullanicidg = new javax.swing.JTextField();
        kullanicisifre = new javax.swing.JPasswordField();
        korku = new javax.swing.JCheckBox();
        romatizm = new javax.swing.JCheckBox();
        komedi = new javax.swing.JCheckBox();
        aksiyon = new javax.swing.JCheckBox();
        belgesel = new javax.swing.JCheckBox();
        bilimdog = new javax.swing.JCheckBox();
        cocukveaile = new javax.swing.JCheckBox();
        gerilim = new javax.swing.JCheckBox();
        drama = new javax.swing.JCheckBox();
        bilimkur = new javax.swing.JCheckBox();
        Register_in = new javax.swing.JButton();
        reality = new javax.swing.JCheckBox();
        anime = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indir (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        kullaniciisim.setBackground(new java.awt.Color(204, 204, 204));
        kullaniciisim.setText("İsminiz:");
        kullaniciisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciisimActionPerformed(evt);
            }
        });

        kullanicimail.setBackground(new java.awt.Color(204, 204, 204));
        kullanicimail.setText("Emailiniz:");
        kullanicimail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicimailActionPerformed(evt);
            }
        });

        kullanicidg.setBackground(new java.awt.Color(204, 204, 204));
        kullanicidg.setText("Doğum Tarihiniz(YYYY-AA-GG)");
        kullanicidg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicidgActionPerformed(evt);
            }
        });

        kullanicisifre.setBackground(new java.awt.Color(204, 204, 204));
        kullanicisifre.setText("jPasswordField1");
        kullanicisifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicisifreActionPerformed(evt);
            }
        });

        korku.setForeground(new java.awt.Color(255, 0, 51));
        korku.setText("KORKU");
        korku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korkuActionPerformed(evt);
            }
        });

        romatizm.setForeground(new java.awt.Color(255, 0, 51));
        romatizm.setText("ROMANTİZM");
        romatizm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romatizmActionPerformed(evt);
            }
        });

        komedi.setForeground(new java.awt.Color(255, 0, 0));
        komedi.setText("KOMEDİ");
        komedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komediActionPerformed(evt);
            }
        });

        aksiyon.setForeground(new java.awt.Color(255, 0, 0));
        aksiyon.setText("AKSİYON VE MACERA");
        aksiyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aksiyonActionPerformed(evt);
            }
        });

        belgesel.setForeground(new java.awt.Color(255, 0, 0));
        belgesel.setText("BELGESEL");
        belgesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belgeselActionPerformed(evt);
            }
        });

        bilimdog.setForeground(new java.awt.Color(255, 0, 0));
        bilimdog.setText("BİLİM VE DOĞA");
        bilimdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilimdogActionPerformed(evt);
            }
        });

        cocukveaile.setForeground(new java.awt.Color(255, 0, 51));
        cocukveaile.setText("ÇOCUK VE AİLE");
        cocukveaile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocukveaileActionPerformed(evt);
            }
        });

        gerilim.setForeground(new java.awt.Color(255, 0, 51));
        gerilim.setText("GERİLİM");
        gerilim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerilimActionPerformed(evt);
            }
        });

        drama.setForeground(new java.awt.Color(255, 0, 51));
        drama.setText("DRAMA");
        drama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dramaActionPerformed(evt);
            }
        });

        bilimkur.setForeground(new java.awt.Color(255, 0, 0));
        bilimkur.setText("BİLİM KURGU VE FANTASTİK YAPIMLAR");
        bilimkur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilimkurActionPerformed(evt);
            }
        });

        Register_in.setBackground(new java.awt.Color(204, 0, 0));
        Register_in.setText("Kayıt Ol");
        Register_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_inActionPerformed(evt);
            }
        });

        reality.setForeground(new java.awt.Color(251, 0, 51));
        reality.setText("Reality Show");
        reality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realityActionPerformed(evt);
            }
        });

        anime.setForeground(new java.awt.Color(251, 0, 51));
        anime.setText("Anime");
        anime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cocukveaile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gerilim))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(romatizm)
                            .addComponent(korku))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(aksiyon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                        .addComponent(bilimdog)
                                        .addGap(51, 51, 51))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bilimkur)
                                        .addGap(61, 61, 61)))
                                .addComponent(reality))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(komedi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(belgesel)
                                        .addGap(63, 63, 63)
                                        .addComponent(drama))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addComponent(anime)))))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullanicidg, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanicimail, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanicisifre, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullaniciisim, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Register_in, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kullaniciisim, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kullanicisifre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kullanicimail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kullanicidg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korku)
                    .addComponent(komedi)
                    .addComponent(belgesel)
                    .addComponent(drama)
                    .addComponent(anime))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reality)
                    .addComponent(bilimdog)
                    .addComponent(aksiyon)
                    .addComponent(romatizm))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilimkur)
                    .addComponent(cocukveaile)
                    .addComponent(gerilim))
                .addGap(53, 53, 53)
                .addComponent(Register_in, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Register_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_inActionPerformed
       

        String sifre = String.valueOf(kullanicisifre.getPassword());
        
        String ekle2 = "INSERT INTO kullanicitablo (kullaniciadi,kullaniciemail,sifre,dogumtarihi,sevdigi1,sevdigi2,sevdigi3) VALUES (?,?,?,?,?,?,?)";
        System.out.println(ekle2);
        try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(ekle2);) {
            pstmt.setString(1, kullaniciisim.getText());
            pstmt.setString(2, kullanicimail.getText());  
            pstmt.setString(3, sifre);
          
            pstmt.setString(4, kullanicidg.getText());
            pstmt.setString(5, secilenler[0]);
            pstmt.setString(6, secilenler[1]);
            pstmt.setString(7, secilenler[2]);

            pstmt.executeUpdate();

              JOptionPane.showMessageDialog(null, "KAYIT BAŞARILI,GİRİŞ YAPABİLİRSİNİZ!");
        } catch (Exception ex) {
            System.out.println("Veri tabanına ekleme başarısız! Hata :" + ex);
        }
        if (sayac == 3) {

           Login_Form fr = new Login_Form();
            fr.setVisible(true);
            fr.pack();
            fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        else   JOptionPane.showMessageDialog(null, "ÇOK FAZLA TÜR SEÇTİNİZ!!");
    }//GEN-LAST:event_Register_inActionPerformed
    
    private void korkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korkuActionPerformed

        if (sayac < 3) {
            secilenler[sayac] = "Korku";
            sayac++;
        }
    }//GEN-LAST:event_korkuActionPerformed


    private void kullanicimailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicimailActionPerformed

    }//GEN-LAST:event_kullanicimailActionPerformed

    private void kullanicisifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicisifreActionPerformed

    }//GEN-LAST:event_kullanicisifreActionPerformed

    private void kullaniciisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciisimActionPerformed

    }//GEN-LAST:event_kullaniciisimActionPerformed

    private void kullanicidgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicidgActionPerformed

    }//GEN-LAST:event_kullanicidgActionPerformed

    private void aksiyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aksiyonActionPerformed
     if (sayac < 3) {
            secilenler[sayac] = "Aksiyon ve Macera";
            sayac++;
        }

        /*    String aksiyon="Select * from program where tipi = 'Aksiyon ve Macera' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(aksiyon);){
           while(rs.next()){
               ab=rs.getString("progadi");
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
           
      
                 
          }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/

    }//GEN-LAST:event_aksiyonActionPerformed

    private void komediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komediActionPerformed
        if (sayac < 3) {
            secilenler[sayac] = "Komedi";
            sayac++;
        }

        /*     String bilim="Select * from program where tipi = 'Komedi' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(bilim);){
           while(rs.next()){
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
        
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/
    }//GEN-LAST:event_komediActionPerformed

    private void belgeselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belgeselActionPerformed
   if (sayac < 3) {
            secilenler[sayac] = "Belgesel";
            sayac++;
        }

        /*    String gerilim="Select * from program where tipi = 'Belgesel' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(gerilim);){
           while(rs.next()){
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
           
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/
    }//GEN-LAST:event_belgeselActionPerformed

    private void dramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dramaActionPerformed
       if (sayac < 3) {
            secilenler[sayac] = "Dram";
            sayac++;
        }

        /*    String gerilim="Select * from program where tipi = 'Drama' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(gerilim);){
           while(rs.next()){
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/
    }//GEN-LAST:event_dramaActionPerformed

    private void romatizmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romatizmActionPerformed
      if (sayac < 3) {
            secilenler[sayac] = "Romantik";
            sayac++;
        }

        /*  String gerilim="Select * from program where tipi = 'Romantik' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(gerilim);){
           while(rs.next()){
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/
    }//GEN-LAST:event_romatizmActionPerformed

    private void bilimdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilimdogActionPerformed
   if (sayac < 3) {
            secilenler[sayac] = "Bilim ve Doğa";
            sayac++;
        }

        /*  String gerilim="Select * from program where tipi = 'Bilim ve Doğa' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(gerilim);){
           while(rs.next()){
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/
    }//GEN-LAST:event_bilimdogActionPerformed

    private void gerilimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerilimActionPerformed
      if (sayac < 3) {
            secilenler[sayac] = "Gerilim";
            sayac++;
        }

        /*   String gerilim="Select * from program where tipi = 'Gerilim' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(gerilim);){
           while(rs.next()){
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
         */
    }//GEN-LAST:event_gerilimActionPerformed

    private void cocukveaileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocukveaileActionPerformed
    if (sayac < 3) {
            secilenler[sayac] = "Çocuk ve Aile";
            sayac++;
        }

        /*    String gerilim="Select * from program where tipi = 'Çocuk ve Aile' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();
               Statement st=conn.createStatement();
               ResultSet rs=st.executeQuery(gerilim);){
           while(rs.next()){
               System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/
    }//GEN-LAST:event_cocukveaileActionPerformed

    private void bilimkurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilimkurActionPerformed
    if (sayac < 3) {
            secilenler[sayac] = "Bilim Kurgu";
            sayac++;
        }

        /* String gerilim="Select * from program where tipi = 'Bilim Kurgu ve Fantastik Yapımlar' order by puanlama desc LIMIT 0,2";
         try(Connection conn=connect();  Statement st=conn.createStatement(); ResultSet rs=st.executeQuery(gerilim);){
           while(rs.next()){
              System.out.println("\tkullaniciismi:"+rs.getString("progadi")+"\tkullaniciemail:"+rs.getString("progid"));
              
  
           }
           
       }catch(Exception ex){
           System.err.println("Veri çekme başarısız!");
       }*/

    }//GEN-LAST:event_bilimkurActionPerformed

    private void animeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animeActionPerformed
       if (sayac < 3) {
            secilenler[sayac] = "Anime";
            sayac++;
        }
    }//GEN-LAST:event_animeActionPerformed

    private void realityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realityActionPerformed
        if (sayac < 3) {
            secilenler[sayac] = "Reality Show";
            sayac++;
        }
    }//GEN-LAST:event_realityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Connection c = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/veritabanları", "root", "");
        } catch (Exception e) {
            System.err.println("Veri tabanı bağlantısı başarısız!");
            System.exit(0);
        }
        System.out.println("Veri tabanına başarılı bir şekilde bağlanıldı.");

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register_in;
    private javax.swing.JCheckBox aksiyon;
    private javax.swing.JCheckBox anime;
    private javax.swing.JCheckBox belgesel;
    private javax.swing.JCheckBox bilimdog;
    private javax.swing.JCheckBox bilimkur;
    private javax.swing.JCheckBox cocukveaile;
    private javax.swing.JCheckBox drama;
    private javax.swing.JCheckBox gerilim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox komedi;
    private javax.swing.JCheckBox korku;
    private javax.swing.JTextField kullanicidg;
    private javax.swing.JTextField kullaniciisim;
    private javax.swing.JTextField kullanicimail;
    private javax.swing.JPasswordField kullanicisifre;
    private javax.swing.JCheckBox reality;
    private javax.swing.JCheckBox romatizm;
    // End of variables declaration//GEN-END:variables
}
